# custom_benchmark_node:
#   ros__parameters:
#     # Wymuszenie OMPL zamiast CHOMP
#     warehouse_plugin: "warehouse_ros_sqlite::DatabaseConnection"
#     ompl:
#       planning_plugin: "ompl_interface/OMPLPlanner"
      
#     benchmark_config:
#       parameters:
#         name: "ur5e_planner_comparison"
#         runs: 5
#         group: "ur_manipulator"
#         timeout: 10.0
#         output_directory: "/home/jakub/Ros/custom_benchmark_ws/results/"
        
#         # Filtry przepuszczające (oba warianty bo sie bugowalo czasem)
#         queries_regex: ".*"
#         query_regex: ".*"
#         start_states_regex: ".*"
#         start_state_regex: ".*"
#         goal_constraints_regex: ".*"
#         goal_constraint_regex: ".*"
#         path_constraints_regex: ".*"
#         path_constraint_regex: ".*"
#         trajectory_constraints_regex: ".*"
#         trajectory_constraint_regex: ".*"


custom_benchmark_node:
  ros__parameters:
    warehouse_plugin: "warehouse_ros_sqlite::DatabaseConnection"
    
    ompl:
      planning_plugin: "ompl_interface/OMPLPlanner"
    chomp:
      planning_plugin: "chomp_interface/CHOMPPlanner"
      
    benchmark_config:
      parameters:
        name: "ur5e_planner_comparison"
        runs: 2
        group: "ur_manipulator"
        timeout: 2.0
        output_directory: "/home/jakub/Ros/custom_benchmark_ws/results/"
        
        planners:
          - plugin: ompl
            planners:
              - RRTConnectkConfigDefault
              - PRMkConfigDefault
              - RRTstarkConfigDefault
              - AnytimePathShortening
          - plugin: chomp
            planners:
              - CHOMP

        # Filtry przepuszczające
        queries_regex: ".*"
        query_regex: ".*"
        start_states_regex: ".*"
        start_state_regex: ".*"
        goal_constraints_regex: ".*"
        goal_constraint_regex: ".*"
        path_constraints_regex: ".*"
        path_constraint_regex: ".*"
        trajectory_constraints_regex: ".*"
        trajectory_constraint_regex: ".*"